apiVersion: v1
kind: Service
metadata:
  name: icinga2
  labels:
    app: icinga2
spec:
  ports:
    - port: 5665
      targetPort: 5665
      name: api
  selector:
    app: icinga2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icinga2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icinga2
  template:
    metadata:
      labels:
        app: icinga2
    spec:
      hostname: icinga2
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: icinga2
          image: icinga/icinga2:2.14.2
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 5665
          env:
            - name: ICINGA2_FEATURE_MONITORING
              value: "true"
          volumeMounts:
            - name: run-dir
              mountPath: /run
      volumes:
        - name: run-dir
          emptyDir: {}
