apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  namespace: monitoring
  labels:
    release: monitoring # Doit correspondre au nom de ton installation helm kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: otel-collector
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 15s
