apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: podinfo
  namespaceSelector:
    matchNames:
      - production
      - staging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
