{
 "title": "Podinfo / Service Health",
 "tags": [
  "podinfo",
  "app"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Application Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (service, namespace)",
     "legendFormat": "{{namespace}}/{{service}} - Requests/s"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status=~\"5..\"}[1m])) by (service, namespace)",
     "legendFormat": "{{namespace}}/{{service}} - Errors"
    }
   ]
  },
  {
   "title": "Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} - P99 Latency"
    }
   ]
  }
 ]
}